{% set name = "ExMAS" %}
{% set version = "0.9.99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a91239d6770d60780cab2d916b2d1bb4bd649d19c44eb85fda5faeb76544450e

build: 
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host: 
    - pip
    - python
  run:
    - python
    - "osmnx"
    - "dotmap>=1.2.20"

about:
  home: https://github.com/RafalKucharskiPK/ExMAS
  summary: 'Exact Matching of Attractive Shared rides (ExMAS) for system-wide strategic evaluations'
  description: |
    Exact Matching of Attractive Shared rides (ExMAS) for system-wide strategic evaluations.
    Scalable off-line strategic utility-based ride-pooling algorithm.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wwydmanski